### PR TITLE
Removed cronet dependencies 

### PR DESCRIPTION
**Pull request by rockenbf**
The cronet libraries are not being build (to the best of my knowledge only used for android) and are therefore a missing dependency.

### CODE REVIEW

**Comment by mintar** [comment]
I needed this PR too in order to fix the broken build on Noetic.

@BillWSY , @garaemon : Could you merge this PR and create a new release, please?

**Comment by garaemon** [comment]
@mintar 
Got it. I'm checking this change in my local environment. I'll get back to you soon.

**Comment by garaemon** [comment]
@mintar 
I just opened a PR to release a new version.
https://github.com/ros/rosdistro/pull/37219

**Comment by garaemon** [comment]
@mintar It's merged. https://mail.google.com/mail/u/0/#inbox/FMfcgzGsmWxzJqvPrFZbzjmjGhwLxFsz
Please wait for the next release of the packages 😄

**Comment by mintar** [comment]
Thanks a lot!

**Pull request merged**
